### ISSUE TITLE
Exception: Couldn't load font ../Matrix_Support_Files/fonts/10x20.bdf

### ISSUE THREAD

**Issue by digitalurban** [techahoynyc/SmartMatrix#14]
Morning   - I have run the requirements etc and connected to MQTT but i get the following:

Connected with result code 0
Press CTRL-C to stop sample
Traceback (most recent call last):
  File "client_runtext.py", line 76, in <module>
    if (not run_text.process()):
  File "/SmartMatrix/samplebase.py", line 69, in process
    self.run()
  File "client_runtext.py", line 38, in run
    font.LoadFont("../Matrix_Support_Files/fonts/10x20.bdf")
  File "graphics.pyx", line 32, in rgbmatrix.graphics.Font.LoadFont
Exception: Couldn't load font ../Matrix_Support_Files/fonts/10x20.bdf

Any help would be great...

Andy

**Comment by digitalurban** [comment]
Closing - moved the install and used the library font...
